### ISSUE TITLE
Filter

### ISSUE THREAD

**Issue by Saquith** [Saquith/IBV2016#6]
Filter gelabelde objecten op basis van zoekcriteria, evt met gradient (most like vs least like)

**Comment by timbakx** [comment]
een idee om hier te kijken naar een minimal bounding box en de rectangularity te bepalen?
(oppervlakte object)/(oppervlakte boudingbox) ligt heel dicht bij 1 als het object rechthoekig is

**Comment by Saquith** [comment]
kan dat ook op schuine objects?

**Comment by timbakx** [comment]
volgens mij wel, ik zal het nog even doorlezen, maar die bounding box moet je dan draaien

**Comment by Saquith** [comment]
klinkt goed iig
